runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.php


env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/FireCatwifi;dbname=catifi
  MYSQL_USER: catwifi808
  MYSQL_PASSWORD: 1
